config/routes.rb
OdimProj2::Application.routes.draw do
  
  
  get '/login' => 'sessions#new', :as => 'login'
  get '/logout' => 'sessions#destroy', :as => 'logout'
  get '/signup' => 'users#new', :as => 'signup'
  get '/users/:id/bag' => 'users#bag', :as => 'bag'
  get '/users/:id/room' => 'users#room', :as => 'room'
  ##get '/history' => 'users#history', :as => 'history'
  get '/users/:id/addto' => 'items#addto', :as => 'addto'
  get '/users/:id/removefrom' => 'items#removefrom', :as => 'removefrom'
  get '/checkout' => 'items#checkout', :as => 'checkout'
  ##delete '/items/:id/removephoto' => 'items#removephoto', :as => 'removephoto'
 
  
  resources :sessions, :only => [:create]
  resources :items
  resources :users

  root :to => 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :kerberos, :password, :password_confirmation
  has_one :room, :foreign_key => 'user_id', :dependent => :nullify ## Every user must have a bag and room
  has_one :bag, :foreign_key => 'user_id', :dependent => :nullify  ## associated with it, to buy and sell.
  has_many :items, :through => :room
  has_many :items, :through => :bag
  
  validates :kerberos, :presence => true
  validates :password, :presence => true
  
  before_save :encrypt_password
  after_save :clear_password 
  

  def self.authenticate(kerberos, password)
    u = User.where(:kerberos => kerberos).first
    if u && u.password_hash == BCrypt::Engine.hash_secret(password, u.password_salt)
      return u
    else
      return nil
    end
  end
  
  def encrypt_password
	if password.present?
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end
  end
  
  def clear_password
	self.password = nil
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ## handles how to show user information, including bag ##
  ## and room information.  creates and deletes users.   ##
  
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
	@user = User.find(params[:id])
	i = Item.check_timeout() ##checks if item has timedout and should be unclaimed
	
	unless session[:user_id] == @user.id ### current user can only visit its own page
      flash[:notice] = "You don't have access to that page!"
      redirect_to user_path(session[:user_id])
      return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @room = @user.build_room
    @bag = @user.build_bag
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    unless session[:user_id] == @user.id ## current user can only edit its own information
      flash[:notice] = "You don't have access to that page!"
      redirect_to user_path(session[:user_id])
      return
    end
  end

  # POST /users
  # POST /users.json
  def create
    ## creating a new user also creates the relative bag and room ##
    @user = User.new(params[:user])
	
    respond_to do |format|
      if @user.save
		@room = Room.new(params[:room])
		@room.update_attributes(:kerberos => @user.kerberos, :user_id => @user.id) ## room
		@bag = Bag.new(params[:bag])
		@bag.update_attributes(:kerberos => @user.kerberos, :user_id => @user.id) ## bag
		session[:user_id] = @user.id
		if @room.save && @bag.save
			format.html { redirect_to login_path, notice: 'User was successfully created.' }
			format.json { render json: @user, status: :created, location: @user }
		else
			format.html { render action: "new" }
			format.json { render json: @user.errors, status: :unprocessable_entity }
		end
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    unless session[:user_id] == @user.id
      flash[:notice] = "You don't have access to that page!"
      redirect_to user_path(session[:user_id])
      return
    end

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    unless session[:user_id] == @user.id
      flash[:notice] = "You don't have access to that page!"
      redirect_to user_path(session[:user_id])
      return
    end
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  # GET /users/1/bag
  # GET /users/1/bag.json
  def bag
    ## shows items that have been added to the bag in view ##
	@user = current_user
	i = Item.check_timeout() ##checks if item has timedout and should be unclaimed

    respond_to do |format|
      format.html # bag.html.erb
      format.json { render json: @user }
    end
  end
  
  # GET /users/1/room
  # GET /users/1/room.json
  def room
    ## shows items user has created in room, in the view ##
	@user = current_user
	i = Item.check_timeout() ##checks if item has timedout and should be unclaimed

    respond_to do |format|
      format.html # room.html.erb
      format.json { render json: @user }
    end
  end
  
  
  ### not needed now. for a later feature ###
  #def history
	#@bag_id = Bag.where(:user_id => current_user.id).first.id
	#@room_id = Room.where(:user_id => current_user.id).first.id
	#@sold = Items.where(:room_id => @room_id) 
  #end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kerberos %><br />
    <%= f.text_field :kerberos %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <!--<div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/bag.html.erb
<% @bag = Bag.where(:user_id => current_user.id).first %>

<div id="head"><%= current_user.kerberos %>'s Bag</div>
<br/>
<table class='itemlist'>
<tr>
<th></th>
<th>Item</th>
<th>Price</th>
<th>Owner</th>
<th>Unclaimed In</th>
<th></th>
<th></th>
</tr>

<% @bag.items.each do |item| %>
<% if item.status != 'bought' %>
<% @owner = Room.find(item.room_id) %>
<tr>
<td class='image'>
<% if item.photo.exists? then %>
	<%= image_tag item.photo.url(:standard) %>
<% end %>
</td>
<td><%= link_to item.name, item %></td>
<td><%= number_to_currency(item.price) %></td>
<td><%= User.find(@owner.user_id).kerberos %></td>
<td><%= ((3600 - (Time.now.utc - item.updated_at.utc))/60).ceil %>mins</td>
<td><%= link_to 'Remove Item from Bag', removefrom_path(item.id) %></td>
<td></td>
</tr>
<% end %>
<% end %>
<tr>
<td><%= link_to 'Checkout', checkout_path, :confirm => "Are you sure you want to checkout at this time?  This cannot be undone." %></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</table>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/history.html.erb
<% @room = Room.where(:kerberos => @user.kerberos).first %>
<p id="notice"><%= notice %></p>

<h2>Welcome to your Dorm Room <%= @user.kerberos %>!</h2>
<p>Below you will find your stuff for sale, and purchase from other dormrooms.</p>
<br/>
<h3>Purchases</h3>
<table class='home purchases'>
<tr>
<th></th>
<th>Item</th>
<th>Price</th>
<th>Owner</th>
<th>Date</th>
<th></th>
<th></th>
</tr>

<% Item.where(:room_id => @room.id).each do |item| %>
<tr>
<td class='image'><img src=<%= item.image %> /></td>
<td><%= item.name %></td>
<td><%= number_to_currency(item.price) %></td>
<td><%= item.room.kerberos %></td>
<td><%= item.date_updated %></td>
<td></td>
<td></td>
</tr>
<% end %>
<br/>
<%= link_to 'Shop Around', items_path %> |
<%= link_to 'Your Bag', users_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', sessions_path %>

app/views/users/room.html.erb
<% @room = Room.where(:kerberos => @user.kerberos).first %>
<p id="notice"><%= notice %></p>

<div id="head"><%= @user.kerberos %>'s DormRoom</div>
<p>Below you will find your stuff for sale, and purchase from other dormrooms.</p>
<br/>
<h3>Selling</h3>
<table class='itemlist'>
<tr>
<th></th>
<th>Item</th>
<th>Price</th>
<th>Status</th>
<th>Description</th>
<th></th>
<th></th>
</tr>

<% Item.where(:room_id => @room.id).each do |item| %>
<tr>
<td class='image'><%= image_tag item.image.url(:standard) %></td>
<td><%= link_to item.name, item %></td>
<td><%= number_to_currency(item.price) %></td>
<td><%= item.status %></td>
<td><%= item.description %></td>
<td><%= link_to 'Delete', item, method: :delete, :confirm => 'Are you sure you want to delete this item from your dormroom?' %></td>
<td><%= link_to 'Edit', edit_item_path(item) %></td>
</tr>
<% end %>
<%= link_to 'Add Item', new_item_path %>
<br/>

app/views/users/show.html.erb
<% @room = Room.where(:user_id => @user.id).first %>

<div id="head"><%= @user.kerberos %>'s DormRoom</div>
<p>Below you will find your items for sale, your previous purchases, and previous sales.  Add new items, and edit those already for sale.  Visit The Lounge to see what you can claim right now.</p>
<br/>
<h3>Selling</h3>
<!--<p class="mini"><%= link_to 'see more', room_path %></p>-->
<table class='itemlist'>
	<tr>
		<th></th>
		<th>Item</th>
		<th>Price</th>
		<th>Status</th>
		<th>Description</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% Item.where(:room_id => @room.id).each do |item| %>
		<% if item.status != 'bought' %>
	<tr>
		<td class='image'>
			<% if item.photo.exists? then %>
				<%= image_tag item.photo.url(:thumb) %>
			<% end %>
		</td>
		<td><%= link_to item.name, item %></td>
		<td><%= number_to_currency(item.price) %></td>
		<td><%= item.status %></td>
		<td><%= item.description %></td>
		<td><%= link_to 'Delete', item, method: :delete, :confirm => 'Are you sure you want to delete this item from your dormroom?' %></td>
		<td>
			<% if item.status == 'active' %>
				<%= link_to 'Edit', edit_item_path(item) %>
			<% else %>
				Claimed by <%= User.find(item.bag_id).kerberos %>
			<% end %>
		</td>
		<td></td>
		<td></td>
	</tr>
		<% else %>		
	<tr>
		<td class='image'></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
		<% end %>
	<% end %>
</table>

<%= link_to 'Add Item', new_item_path %>
<br/>
<br/>
<h3>Purchases</h3><!--<% link_to 'see more', bag_path %>-->
<table class='itemlist'>
	<tr>
		<th></th>
		<th>Item</th>
		<th>Price</th>
		<th>Owner</th>
		<th>Date</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
	</tr>

	<% @bag = Bag.where(:user_id => current_user.id).first %>
	<% @bag.items.each do |item| %>
		<% if item.status == 'bought' %>
			<% @kerberos = User.find(@room.user_id).kerberos %>
	<tr>
		<td class='image'>
			<% if item.photo.exists? then %>
				<%= image_tag item.photo.url(:thumb) %>
			<% end %>
		</td>
		<td><%= link_to item.name, item %></td>
		<td><%= number_to_currency(item.price) %></td>
		<td><%= @kerberos %></td>
		<td><%= item.updated_at %></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
		<% else %>		
	<tr>
		<td class='image'></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
		<% end %>
	<% end %>
</table>

<br/>
<br/>
<h3>Sales</h3><!--<% link_to 'see more', bag_path %>-->
<table class='itemlist'>
<tr>
<th></th>
<th>Item</th>
<th>Price</th>
<th>Status</th>
<th>Description</th>
<th></th>
<th></th>
</tr>

<% Item.where(:room_id => @room.id).each do |item| %>
<% if item.status == 'bought' %>
<tr>
<td class='image'>
<% if item.photo.exists? then %>
	<%= image_tag item.photo.url(:thumb) %>
<% end %>
</td>
<td><%= link_to item.name, item %></td>
<td><%= number_to_currency(item.price) %></td>
<td><%= item.status %></td>
<td><%= item.description %></td>
<td></td>
<td></td>
</tr>
<% else %>		
	<tr>
		<td class='image'></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
		<% end %>
	<% end %>
</table>