config/routes.rb
OdimProj2::Application.routes.draw do
  
  
  get '/login' => 'sessions#new', :as => 'login'
  get '/logout' => 'sessions#destroy', :as => 'logout'
  get '/signup' => 'users#new', :as => 'signup'
  get '/users/:id/bag' => 'users#bag', :as => 'bag'
  get '/users/:id/room' => 'users#room', :as => 'room'
  ##get '/history' => 'users#history', :as => 'history'
  get '/users/:id/addto' => 'items#addto', :as => 'addto'
  get '/users/:id/removefrom' => 'items#removefrom', :as => 'removefrom'
  get '/checkout' => 'items#checkout', :as => 'checkout'
  ##delete '/items/:id/removephoto' => 'items#removephoto', :as => 'removephoto'
 
  
  resources :sessions, :only => [:create]
  resources :items
  resources :users

  root :to => 'sessions#new'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :room
  belongs_to :bag
  attr_accessible :description, :photo, :name, :price, :price, :status, :room_id, :bag_id, :photo_file_name, :photo_content_type, :photo_file_size
  
  validates :name, :presence => true
  validates :price, :presence => true
  validates :room_id, :presence => true

  attr_accessor :photo_file_name
  attr_accessor :photo_content_type
  attr_accessor :photo_file_size
  attr_accessor :photo_updated_at
  
  ### PICTURE UPLOADS ###
  ### no photos being added or removed currently ##
  has_attached_file :photo, :styles => { :thumb=> "100x100#",
										:standard  => "400x400>" },
							:url  => "/assets/items/:id/:style/:basename.:extension",
							:path => ":rails_root/public/assets/items/:id/:style/:basename.:extension"

  #validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 15.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
  ########################
  
  ### checks which items are now unclaimed ###
  def self.check_timeout()
	Item.all.each do |item|
		update = Time.now.utc - item.updated_at.utc
		if item.status == 'claimed' && update > 3600 ## becomes unclaimed after an hour
			item.update_attributes(:status => 'active')
			@bag = Bag.find(item.bag_id)
			@bag.items.delete(item)
			
		end 
	end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #provides methods to add, delete, edit and show items, as well as
  #changing statuses based on the current user's actions.
  
  
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    i = Item.check_timeout() ##checks if item has timedout and should be unclaimed

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    i = Item.check_timeout()
    
    ## checks if user should be seeing this item and directs back to dormroom page
	if @item.status == 'bought' && @item.bag_id != session[:user_id] && @item.room_id != session[:user_id]
	  flash[:notice] = "This item is no longer available."
      redirect_to items_path
      return
	end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
    
    ## checks if item is still editable and if the user owns the item, redirects to user dormroom page
    unless @item.room_id == session[:user_id] && @item.status == 'active'
	  flash[:notice] = "You don't have access to that page!"
      redirect_to user_path(session[:user_id])
      return
	end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])
    
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1/addto
  # GET /items/1/addto.json
  def addto
	@bag = Bag.where(:user_id => current_user.id).first
	@item = Item.find(params[:id])
	@bag.items << @item ## given item, adds to current users bag
    respond_to do |format|
      if @bag.save
		@item.update_attribute(:status, 'claimed')
        format.html { redirect_to bag_path(current_user), notice: 'Item was successfully added to your bag.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /items/1/removefrom
  # GET /items/1/removefrom.json
  def removefrom
	@bag = Bag.where(:user_id => current_user.id).first
	@item = Item.find(params[:id])
	@bag.items.delete(@item)
    respond_to do |format|
      if @bag.save
		@item.update_attribute(:status, 'active')
        format.html { redirect_to bag_path(current_user), notice: 'Item was successfully deleted from your bag.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end
  
## currently no photos being added or removed ##
  #def removephoto
	#@item = Item.find(params[:id])
	#@item.photo.destroy
	#if @item.save
		#respond_to do |format|
		  #format.html { redirect_to edit_item_path(@item), notice: 'Checkout successful!' }
		  #format.json { head :no_content }
		#end
	#end
  #end
#####################################
  
  
  # GET /checkout
  # GET /checkout.json
  def checkout
  ### eventually will send an email or something ###
  ## currently just adds item to your bought list ##
	current_bag.items.each do |item|
		item.update_attribute(:status,'bought')
	end
	respond_to do |format|
      format.html { redirect_to user_path(current_user), alert: 'Checkout successful!' }
      format.json { head :no_content }
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user) }
      format.json { head :no_content }
    end
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :multipart => true } do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
		<% @item.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
		<%= f.hidden_field :room_id, :value => current_room.id %>
		<%= f.hidden_field :status, :value => 'active' %>
    </div>
    <div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
    </div>
    <div class="field">
		<%= f.label :price %><br />
		$<%= f.text_field :price %>
    </div>
    <div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description %>
    </div>

<!-- PHOTOS CURRENTLY NOT BEING ADDED OR REMOVED -->
  <!--<div class="field">
	<%= f.label :photo %><br />
	<%= f.file_field :photo %>
	<% if @item.photo.exists? then %>
		<p>Current Photo</>
		<%= image_tag @item.photo.url(:thumb) %>
		<%= link_to 'Remove Photo', removephoto_path(@item), method: :delete, :confirm => 'Are you sure you want to remove this photo?' %>
	<% end %>
  </div>-->
<!-- ########################################### -->

    <div class="actions">
		<%= f.submit %>
    </div>
<% end %>

app/views/items/edit.html.erb
<div id="head" >Edit Item</div>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div id="head">The Lounge</div>

<table class='itemlist'>
  <tr>
    <th></th>
    <th>Item</th>
    <th>Owner</th>
    <th>Status</th>
    <th>Price</th>
    <th>Description</th>
    <th></th>
  </tr>

<% @items.reverse.each do |item| %>
	<% if item.status != 'bought' %>
		<% @room = Room.find(item.room_id) #the Room this item is in %>
		<% @owner = User.find(@room.user_id).kerberos %>
  <tr>
    <td class='image'>
		<% if item.photo.exists? then %>
			<%= link_to item do %><p><%= image_tag item.photo.url(:standard) %></p><% end %>
		<% end %>
	</td>
    <td><%= link_to item.name, item %></td>
    <td><%= @owner %></td>
    <td><%= item.status %></td>
    <td><%= number_to_currency(item.price) %></td>
    <td><%= item.description %></td>
    <td><% if item.room != current_user.room %>
			<% if item.status == 'claimed' %>
				<% if item.bag_id != current_user.bag.id %>
					Claimed
				<% else %>
					<%= link_to 'In Your Bag Already', bag_path(current_user) %>
				<% end %>
			<% else %>
				<%= link_to 'Add Item to Bag', addto_path(item.id) %>
			<% end %>
		<% elsif item.status != 'claimed' %>
			<%= link_to 'Edit Item', edit_item_path(item) %>
		<% end %>
	</td>
  </tr>	
	<% end %>
<% end %>
  <tr>
	<td class='image'></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
	<td></td>
  </tr>
</table>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<% @room = Room.find(@item.room_id) #the Room this item is in %>
<% @owner = User.where(:id => @room.user_id).first.kerberos %>

<div id="head"><b>Name:</b><%= @item.name %></div>
<div id="show">
<p>
  <% if @item.status == 'active' %>
	This item is in <%= @owner %>'s room.
  <% elsif @item.status == 'claimed' %>
    This item is from <%= @owner %>'s room, claimed by <%= User.find(@item.bag_id).kerberos %>.
  <% else %>
	This item has been purchased.
  <% end %>
</p>

<p><b>Price:</b><%= number_to_currency(@item.price) %></p>
<p><b>Description:</b><%= @item.description %></p>

<% if @item.status == 'active' %>
	<% if @item.room != current_user.room %>
		<p><%= link_to 'Add Item to Bag', addto_path(@item.id) %></p>
	<% else %>
		<p><%= link_to 'Edit Item', edit_item_path(@item.id) %></p>
	<% end %>
<% end %>


<!-- uneeded info currently -->
<!--
<p>
<td class='image'>
<% if @item.photo.exists? then %>
	<%= image_tag @item.photo.url(:thumb) %>
<% end %>
</td>
</p>

<p>
  <b>Status:</b>
  <%= @item.status %>
</p>-->


</div>